// js
import './js/goToTask';
import './js/getDataFromServer';
import './js/dataToConsole';
import './js/ancestry';
import './js/sortingData';
import './js/loadDataWithClick';
// style
import './scss/main.scss';